### ISSUE TITLE
I don't *think* using negative numbers to access arrays is discussed.

### ISSUE THREAD

**Issue by mikeappell** [learn-co-curriculum/array-introduction#2]
Actually, I believe I saw using [-1] to access the last index mentioned in one of the sections, but I think it would be worth adding, wherever seems most relevant, a paragraph on using negative index numbers, e.g. [-1] for last, [-2] for second to last etc, as well as a warning on looping past the first index.

This could also be mentioned where you describe the #first and #last methods, that they're essentially identical to [0] and [-1].

It would probably also be worth mentioning somewhere that you can chain methods together, e.g. array.reverse.each, or that you can also do something like collect.with_index to be able to gain that variable within the block.

**Comment by SophieDeBenedetto** [comment]
hi @mikeappell , 

Thanks for the feedback. I've added a brief section that touches on the stuff you mention above to this reading: https://github.com/learn-co-curriculum/array-readme
